name = "Create: Above the Clouds"
author = "Neplex"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b177b3ba41ceb6e2a62bf5bbc19db38adb086147c0616883f29a949b0977dd12"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
