name = "create-above-the-clouds"
author = "Neplex"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "467863cbb62a397bf39b1139a67bb27f28624a3b34d89c3c2b66c8984742fdfd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
