name = "create-above-the-clouds"
author = "Neplex"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "529cfc97908a21e3318ab854ffd97fd1709c50736721564f6af09176eb415f25"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
