name: Publish Modpack Release

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest
      
      - name: Export Modrinth Pack
        run: |
          packwiz modrinth export
      
      - name: Extract Minecraft Version
        id: pack-meta
        run: |
          MC_VER=$(grep -E '^minecraft[[:space:]]*=' pack.toml | sed -E 's/.*=[[:space:]]*"([^"]+)".*/\1/')
          echo "mc_version=$MC_VER" >> $GITHUB_OUTPUT

      - name: Publication
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: '*.mrpack'
          loaders: neoforge
          game-versions: ${{ steps.pack-meta.outputs.mc_version }}
